default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  port: 5432
  pool: 5

development:
  <<: *default
  database: frat-patchstore_development

test:
  <<: *default
  database: frat-patchstore_test

production:
  <<: *default
  database: frat-patchstore_production
